config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'articles#index'

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# articles model
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
  scope :sorted, -> { order(published_at: :desc, updated_at: :desc) }
  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where('published_at <= ?', Time.current) }
  scope :scheduled, -> { where('published_at >', Time.current) }
  def draft?
    published_at.nil?
  end
  # used to check whether a post s published or not for example to avoid commenting in drafts

  def published?
    published_at? && published_at <= Time.current
  end

  def schedule?
    published_at? && published_at >= Time.current
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# doc
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# doc
class ArticlesController < ApplicationController
  # http_basic_authenticate_with name: "bassem", password: "root", except: [:index, :show]

  before_action :authenticate_user!, except: %i[index show]
  before_action :set_article, except: %i[index new create]
  # if the user is signed in display all the articles else display only the published ones
  def index
    @articles = user_signed_in? ? Article.sorted : Article.published.sorted
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status, :published_at)
  end

  def set_article
    @article = user_signed_in? ? Article.find(params[:id]) : Article.published.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# doc
class CommentsController < ApplicationController
  http_basic_authenticate_with name: 'bassem', password: 'root', only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>
  <div>
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at ,include_blank: true %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1  >Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>
Our blog has
<%= Article.public_count %>
articles and counting!
<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <div>
        <% if article.draft? %>
          <div class=" p-2 rounded bg-gray-100 text-gray-900">
            Draft
          </div>
        <% end %>
      </div>

      <div>
        <% if article.schedule? %>
          <div class=" p-2 rounded bg-gray-100 text-gray-900">
            scheduled
          </div>
        <% end %>
      </div>

        <div>
        <% if article.published? %>
          <div class=" p-2 rounded bg-gray-100 text-gray-900">
            published
          </div>
        <% end %>
      </div>

      <li>
        <%= link_to article.title, article %>
      </li>
    <% end %>
  <% end %>
</ul>

<%= link_to "New Article",
new_article_path,
{
  class:
    "inline-block rounded-md border border-transparent bg-indigo-600 px-8 py-3 text-center font-medium text-white hover:bg-indigo-700"
} %>

app/views/articles/new.html.erb
<h1 >New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1 ><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2 ">Comments</h2>
<%= render @article.comments %>

<h2 ">Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="prose mx-auto">
    <main >

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <div>
        <% if user_signed_in? %>
          <%= link_to "Profile",edit_user_registration_path %>
          <%= button_to "Log_out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Login", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
        <% end %>
       </div>
      <%= yield %>
    </main>
  </body>
</html>